# netlify.toml - Fallback usando dist (que existe)
[build]
  command = "npm run build"
  # Como dist existe, usar como publish directory
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"  
  NPM_VERSION = "10"
  # Forçar preset Netlify
  NITRO_PRESET = "netlify"

# Para site estático, sem redirects para functions
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"