# netlify.toml - Para Node.js server (sem preset)
[build]
  command = "npm run build"
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "18"  
  NPM_VERSION = "10"

# Função para SSR usando Node.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/index.mjs"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/index.mjs"
  status = 200

# Headers para PWA
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"