# netlify.toml - Configuração para Nuxt 3 PWA (usando dist)
[build]
  command = "npm run build"
  # Agora o Nuxt está gerando em dist/
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"  
  NPM_VERSION = "10"

# Headers para PWA
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect para SPA (importante para PWA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200ão para Nuxt 3 PWA
[build]
  command = "npm run build"
  # Nuxt 3 gera em .output/public
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "18"  
  NPM_VERSION = "10"

# Headers para PWA
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"