# netlify.toml - Configuração para Nuxt 3 SSR + PWA
[build]
  command = "npm run build:ssr"
  # Nuxt 3 com preset netlify gera em .output/public
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "18"  
  NPM_VERSION = "10"

# Headers para PWA
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache para assets do Nuxt
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para ícones
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers de segurança para PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Função para roteamento SSR (Netlify Functions)
[functions]
  directory = ".output/server"

# Redirects para SSR (importante - sem isso o SSR não funciona)
[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

# Fallback para páginas não encontradas (404)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200