# netlify.toml - Configuração otimizada para PWA no Netlify
[build]
  command = "npm run generate"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"  
  NPM_VERSION = "10"

# Headers específicos para PWA - CRÍTICOS
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Fallback para extensão .json (alguns browsers antigos)
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers para ícones PWA
[[headers]]
  for = "/icon-*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=31536000, immutable"

# Cache otimizado para assets Nuxt
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers de segurança otimizados para PWA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    # CORS para manifest (importante para alguns casos)
    Access-Control-Allow-Origin = "*"

# Redirects para SPA - essencial para PWA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Redirect explícito para manifest (fallback)
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.webmanifest"
  status = 301

# Edge function para debug de manifest (opcional - remover em produção)
# [[edge_functions]]
#   function = "manifest-debug"
#   path = "/debug/manifest"

# Configurações específicas do Netlify para PWA
[context.production]
  command = "npm run generate"
  
[context.deploy-preview]
  command = "npm run generate"

[context.branch-deploy]
  command = "npm run generate"